/**
 * You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
 */
//--
{
    const findTheDifference = function (s, t) {
        let map = {}
        for (let chars in s) {
            map[s[chars]] = map[s[chars]] ? map[s[chars]] += 1 : 1
        }
        for (let chars in t) {
            map[t[chars]] = map[t[chars]] ? map[t[chars]] -= 1 : 1

        }
        return Object.keys(map).find(key => map[key] === 1); // for(const key in map) { if(map[key] === 1) return key}
    };
}

{
    const findTheDifference = function (s, t) {
        let map = new Map();
        for (let char of t) map.set(char, map.get(char) + 1 || 1);
        for (let char of s) map.set(char, map.get(char) - 1);
        for (let key of map) {
            if (key[1] === 1)
             return key[0];
        }
        return "-1";
    };
    console.log(findTheDifference("abcd", "abcde"))
}

{
    const findTheDifference = function (s, t) {
        let ans = 0;
        for (let i = 0; i < s.length; i++) {
            ans += s[i].charCodeAt();
        }
        for (let j = 0; j < t.length; j++) {
            ans -= t[j].charCodeAt();
        }
        return String.fromCharCode(ans);
    };
}
//   XOR's codes are ALMOST SAME!! Just slightly change operation symbols:

{
    const findTheDifference = function (s, t) {
        let ans = 0;
        for (let i = 0; i < s.length; i++) {
            ans ^= s[i].charCodeAt();
        }
        for (let j = 0; j < t.length; j++) {
            ans ^= t[j].charCodeAt();
        }
        return String.fromCharCode(ans);
    };
}
//Get the key by value in hashmap
{
    let obj = new Map()
   obj.set("a", 1)
   obj.set("g", 5)
   obj.set("i", 3)
   for(let ent of obj){
    console.log(ent,">",ent[1],">", ent[0])
   }
}